### ISSUE TITLE
Error installing roslib and rospy

### ISSUE THREAD

**Issue by codersneha3012** [gorinars/ros_voice_control#1]
Hi,

How can I install roslib and rospy using pip? I could not find it. 

Also while running command "roslaunch turtlebot_gazebo turtlebot_world.launch"
I am getting error - 
[turtlebot_world.launch] is neither a launch file in package [turtlebot_gazebo] nor is [turtlebot_gazebo] a launch file name
The traceback for the exception was written to the log file

Please assist.
Thanks already.

**Comment by priyablue** [comment]
Hi, 

You cannot install ROS libraries using PIP. Instead use sudo apt install python-roslib and  you can clone this package which will install rospy "https://github.com/ros/ros_comm"

This error is because you dont have turtlebot_gazebo package installed in your system. You can check this package and which has all the ros files related to this error. 
https://github.com/turtlebot/turtlebot_simulator
